### ISSUE TITLE
Endpoints enhancement

### ISSUE THREAD

**Issue by TizianoN** [TizianoN/103-boolpress#5]
- Crea un endpoint `/api/author` (only index) che restituisca la lista di tutti gli autori
  - Ricorda che gli autori sono users, ma il controller si chiamerà AuthorsController
  - Le uniche informazioni rilevanti sono id e nome
 
- prevedi e gestisci filtri per `author` e `title` nella API per gli advanced filters
  - l'author potrebbe arrivare un valore int nella chiave `activeAuthor` rappresentate id_user come chiave in `$filters`
  - Per il title potrebbe arrivare una porzione di titolo (valore str) nella chiave `searchedTitle` in `$filters`.

**Comment by AndreaCoggio94** [comment]
AuthorController non Authors
